# student-api.yml
openapi: 3.0.0
info:
  title: "SMS3000"
  description: "An API about students and grades"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Student:
      type: "object"
      required:
        - last_name
        - first_name
      properties:
        student_id:
          type: "integer"
        first_name:
          type: "string"
        last_name:
          type: "string"
        email:
          type: "string"
        phone:
          type: "string"
  parameters:
    last_name:
      name: "last_name"
      description: "Last name of the Student to get."
      in: path
      required: True
      schema: 
        type: "string"
    student_id:
      name: "student_id"
      description: "Unique identifier for student"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /student:
    get:
      operationId: "student.read_all"
      tags:
        - "Students"
      summary: "Read the list of students"
      responses:
        "200":
          description: "Successfully read student list"
    post:
      operationId: "student.create"
      tags:
        - "Students"
      summary: "Create a student"
      requestBody:
        description: "Student to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "student"
              $ref: "#/components/schemas/Student"
      responses:
        "201":
          description: "Successfully created student"
  /student/{student_id}:
    get:
      operationId: "student.read_one"
      tags:
        - Students
      summary: "Read one student"
      parameters:
        - $ref: "#/components/parameters/student_id"
      responses:
        "200":
          description: "Successfully read student"
        "404":
          description: "Not found"
    put:
      operationId: "student.update"
      tags:
        - Students
      summary: "Update a student"
      parameters:
        - $ref: "#/components/parameters/student_id"
      responses:
        "200":
          description: "Successfully updated student"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "student"
              $ref: "#/components/schemas/Student"
    delete:
      operationId: "student.delete"
      tags:
        - Students
      summary: "Delete a student"
      parameters:
        - $ref: "#/components/parameters/student_id"
      responses:
        "204":
          description: "Successfully deleted student"
