services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 81:81
    restart: always
  flask:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
    restart: always
