services:
  flask-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: travel_booking_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwepoi123
      MYSQL_DATABASE: travel_booking
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pQwepoi123"]
      interval: 5s
      timeout: 5s
      retries: 5